# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: iiot.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='iiot.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\niiot.proto\" \n\x11\x44\x65viceDataRequest\x12\x0b\n\x03\x63md\x18\x01 \x01(\t\";\n\x12\x44\x65viceDataResponse\x12\x0b\n\x03\x63md\x18\x01 \x01(\t\x12\x18\n\x07sensors\x18\x02 \x03(\x0b\x32\x07.Sensor\"-\n\x06Sensor\x12\x0e\n\x06\x64\x65vEui\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t2>\n\x03Iot\x12\x37\n\nGetDevices\x12\x12.DeviceDataRequest\x1a\x13.DeviceDataResponse\"\x00\x62\x06proto3')
)




_DEVICEDATAREQUEST = _descriptor.Descriptor(
  name='DeviceDataRequest',
  full_name='DeviceDataRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmd', full_name='DeviceDataRequest.cmd', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=14,
  serialized_end=46,
)


_DEVICEDATARESPONSE = _descriptor.Descriptor(
  name='DeviceDataResponse',
  full_name='DeviceDataResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='cmd', full_name='DeviceDataResponse.cmd', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='sensors', full_name='DeviceDataResponse.sensors', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=107,
)


_SENSOR = _descriptor.Descriptor(
  name='Sensor',
  full_name='Sensor',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='devEui', full_name='Sensor.devEui', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='description', full_name='Sensor.description', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=154,
)

_DEVICEDATARESPONSE.fields_by_name['sensors'].message_type = _SENSOR
DESCRIPTOR.message_types_by_name['DeviceDataRequest'] = _DEVICEDATAREQUEST
DESCRIPTOR.message_types_by_name['DeviceDataResponse'] = _DEVICEDATARESPONSE
DESCRIPTOR.message_types_by_name['Sensor'] = _SENSOR
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

DeviceDataRequest = _reflection.GeneratedProtocolMessageType('DeviceDataRequest', (_message.Message,), dict(
  DESCRIPTOR = _DEVICEDATAREQUEST,
  __module__ = 'iiot_pb2'
  # @@protoc_insertion_point(class_scope:DeviceDataRequest)
  ))
_sym_db.RegisterMessage(DeviceDataRequest)

DeviceDataResponse = _reflection.GeneratedProtocolMessageType('DeviceDataResponse', (_message.Message,), dict(
  DESCRIPTOR = _DEVICEDATARESPONSE,
  __module__ = 'iiot_pb2'
  # @@protoc_insertion_point(class_scope:DeviceDataResponse)
  ))
_sym_db.RegisterMessage(DeviceDataResponse)

Sensor = _reflection.GeneratedProtocolMessageType('Sensor', (_message.Message,), dict(
  DESCRIPTOR = _SENSOR,
  __module__ = 'iiot_pb2'
  # @@protoc_insertion_point(class_scope:Sensor)
  ))
_sym_db.RegisterMessage(Sensor)



_IOT = _descriptor.ServiceDescriptor(
  name='Iot',
  full_name='Iot',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=156,
  serialized_end=218,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetDevices',
    full_name='Iot.GetDevices',
    index=0,
    containing_service=None,
    input_type=_DEVICEDATAREQUEST,
    output_type=_DEVICEDATARESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_IOT)

DESCRIPTOR.services_by_name['Iot'] = _IOT

# @@protoc_insertion_point(module_scope)
