# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import protos.iiot_pb2 as iiot__pb2


class IotStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.GetDevices = channel.unary_unary(
        '/Iot/GetDevices',
        request_serializer=iiot__pb2.DeviceDataRequest.SerializeToString,
        response_deserializer=iiot__pb2.DeviceDataResponse.FromString,
        )


class IotServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def GetDevices(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_IotServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'GetDevices': grpc.unary_unary_rpc_method_handler(
          servicer.GetDevices,
          request_deserializer=iiot__pb2.DeviceDataRequest.FromString,
          response_serializer=iiot__pb2.DeviceDataResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'Iot', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
